import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  ArrowDown, ArrowUpRight, AtSign, Camera, Code2, Dumbbell, Gamepad2, Globe,
  Heart, Mail, Sparkles, Star, Trophy, Tv, Waves, Zap,
} from 'lucide-react';
import './styles.css';
import './liquid.css';

const SPLASH_KEY = 'cj-site-splash-seen-v1';

const NAV = [
  ['about', 'About'],
  ['hobbies', 'Hobbies'],
  ['projects', 'Projects'],
  ['favorites', 'Favorites'],
  ['contact', 'Contact'],
];

const STATS = [
  { value: '3', label: 'sports & crafts in rotation' },
  { value: '∞', label: 'anime episodes watched' },
  { value: '100%', label: 'proud of the fun fact' },
];

const HOBBIES = [
  {
    icon: Trophy,
    title: 'Tennis',
    tag: 'COURT',
    copy: 'Baseline rallies, second-serve gambles, and the occasional winner down the line. Tennis is where the competitive streak lives.',
    accent: 'a',
  },
  {
    icon: Waves,
    title: 'Swim',
    tag: 'POOL',
    copy: 'Laps before the world wakes up. The quietest part of the day is underwater, counting strokes instead of notifications.',
    accent: 'b',
  },
  {
    icon: Gamepad2,
    title: 'Anime games',
    tag: 'GRIND',
    copy: 'The tagline is not a joke. Gacha pulls, limited events, and dailies done with religious discipline. Too much? Absolutely. Stopping? No.',
    accent: 'c',
  },
  {
    icon: Tv,
    title: 'Anime & TV',
    tag: 'COUCH',
    copy: 'Watching TV a lot is a hobby if you commit to it, and the commitment here is total. Seasonal anime, binges, and strong opinions on all of it.',
    accent: 'd',
  },
  {
    icon: Code2,
    title: 'Coding',
    tag: 'TERMINAL',
    copy: 'Building things for the web — including this very site, which was generated by an AI coding agent and shipped straight to GitHub.',
    accent: 'e',
  },
];

const PROJECTS = [
  {
    name: 'Groupwise',
    kind: 'WEB APP',
    copy: 'A calm, liquid-glass student group randomizer for classrooms. Paste a roster, pick a group count, get balanced teams with a water-reveal animation.',
    link: 'https://github.com/sneezejayhauser/randomizer',
    linkLabel: 'sneezejayhauser/randomizer',
    accent: 'b',
  },
  {
    name: 'cj-about-me',
    kind: 'THIS SITE',
    copy: 'The page you are reading. Dark liquid glass, a letter-by-letter intro, scroll-triggered reveals — built in one shot by Codex from a single prompt.',
    link: 'https://github.com/sneezejayhauser/fat',
    linkLabel: 'sneezejayhauser/fat',
    accent: 'c',
  },
];

const FAVORITES = [
  { icon: Gamepad2, title: 'Anime games', copy: 'The main obsession. Home-screen icons outnumber productivity apps by an embarrassing margin.' },
  { icon: Tv, title: 'Watching TV', copy: 'A lot of it. Comfort shows, seasonal anime, and "one more episode" until it is technically tomorrow.' },
  { icon: Trophy, title: 'Tennis', copy: 'Favorite way to move. Every match is a puzzle played at sprint speed.' },
  { icon: Waves, title: 'Swimming', copy: 'Favorite way to not think. Just water, rhythm, and the black line at the bottom.' },
  { icon: Code2, title: 'Coding', copy: 'Favorite way to make. An idea in the morning, a URL by the evening.' },
  { icon: Star, title: 'Winning', copy: 'The vibe for this site was "I want to win" — so consider this section the victory lap.' },
];

function useReveal() {
  useEffect(() => {
    const nodes = document.querySelectorAll('.reveal');
    const observer = new IntersectionObserver(
      entries => entries.forEach(entry => {
        if (entry.isIntersecting) {
          entry.target.classList.add('revealed');
          observer.unobserve(entry.target);
        }
      }),
      { threshold: 0.12, rootMargin: '0px 0px -40px 0px' },
    );
    nodes.forEach(node => observer.observe(node));
    return () => observer.disconnect();
  }, []);
}

function App() {
  const [showSplash, setShowSplash] = useState(() => {
    try { return localStorage.getItem(SPLASH_KEY) !== '1'; } catch { return true; }
  });
  useEffect(() => {
    if (!showSplash) { try { localStorage.setItem(SPLASH_KEY, '1'); } catch {} }
  }, [showSplash]);
  useReveal();

  return <>
    {showSplash && <SplashScreen onFinish={() => setShowSplash(false)} />}
    <header className="topbar">
      <a className="brand" href="#top"><span className="brand-mark"><Sparkles size={18} /></span>CJ</a>
      <nav className="top-nav" aria-label="Sections">
        {NAV.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}
      </nav>
      <div className="top-actions">
        <a className="button button-ghost" href="https://github.com/sneezejayhauser" target="_blank" rel="noreferrer"><Globe size={15} /> GitHub</a>
      </div>
    </header>

    <main className="app-shell" id="top">
      <section className="hero">
        <div>
          <p className="eyebrow">PERSONAL SITE <span className="eyebrow-dot" /></p>
          <h1>CJ plays anime games <em>too much.</em></h1>
          <p className="hero-copy">Also: tennis, swim, coding, and watching TV a lot. This is the official record — dark, glassy, and built to win.</p>
          <div className="hero-actions">
            <a className="button button-primary" href="#about"><ArrowDown size={15} /> Meet CJ</a>
            <a className="button" href="https://www.instagram.com/sneezejayhauser" target="_blank" rel="noreferrer"><Camera size={15} /> @sneezejayhauser</a>
          </div>
        </div>
        <div className="hero-decoration" aria-hidden="true"><Gamepad2 /><span>✦</span></div>
      </section>

      <section className="stat-strip reveal">
        {STATS.map(stat => (
          <div className="stat" key={stat.label}>
            <strong>{stat.value}</strong>
            <span>{stat.label}</span>
          </div>
        ))}
      </section>

      <section className="section" id="about">
        <div className="section-heading reveal">
          <p className="section-kicker">ABOUT</p>
          <h2>A person of <em>many lanes.</em></h2>
        </div>
        <div className="about-grid">
          <article className="panel reveal">
            <p className="lede">CJ does tennis, swims, and codes — and enjoys watching TV a lot. Not as a guilty pleasure. As a discipline.</p>
            <p>The week splits cleanly: court time and pool time for the body, code for the brain, and anime — shows and especially games — for everything else. The tagline says "too much" and the tagline is accurate.</p>
          </article>
          <article className="panel fun-fact reveal" style={{ '--reveal-delay': '120ms' }}>
            <p className="section-kicker">FUN FACT</p>
            <p className="fun-fact-text">CJ still eats his boogers — and is proud of it, and loves it.</p>
            <p className="fun-fact-note">This fact was submitted personally, on the record, with full confidence. No notes.</p>
          </article>
        </div>
      </section>

      <section className="section" id="hobbies">
        <div className="section-heading reveal">
          <p className="section-kicker">HOBBIES</p>
          <h2>The <em>rotation.</em></h2>
        </div>
        <div className="hobby-grid">
          {HOBBIES.map((hobby, index) => (
            <article className={`hobby-card accent-${hobby.accent} reveal`} style={{ '--reveal-delay': `${index * 90}ms` }} key={hobby.title}>
              <div className="hobby-top">
                <hobby.icon size={22} />
                <span>{hobby.tag}</span>
              </div>
              <h3>{hobby.title}</h3>
              <p>{hobby.copy}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="section" id="projects">
        <div className="section-heading reveal">
          <p className="section-kicker">PROJECTS</p>
          <h2>Things that <em>shipped.</em></h2>
        </div>
        <div className="project-grid">
          {PROJECTS.map((project, index) => (
            <article className={`project-card accent-${project.accent} reveal`} style={{ '--reveal-delay': `${index * 120}ms` }} key={project.name}>
              <div className="project-top">
                <span className="project-kind">{project.kind}</span>
                <Zap size={16} />
              </div>
              <h3>{project.name}</h3>
              <p>{project.copy}</p>
              <a href={project.link} target="_blank" rel="noreferrer">{project.linkLabel} <ArrowUpRight size={14} /></a>
            </article>
          ))}
        </div>
      </section>

      <section className="section" id="favorites">
        <div className="section-heading reveal">
          <p className="section-kicker">FAVORITE THINGS</p>
          <h2>The <em>hall of fame.</em></h2>
        </div>
        <div className="favorites-grid">
          {FAVORITES.map((fav, index) => (
            <article className="favorite-card reveal" style={{ '--reveal-delay': `${index * 70}ms` }} key={fav.title}>
              <fav.icon size={19} />
              <h3>{fav.title}</h3>
              <p>{fav.copy}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="section" id="contact">
        <div className="section-heading reveal">
          <p className="section-kicker">CONTACT</p>
          <h2>Say <em>hi.</em></h2>
        </div>
        <div className="contact-grid">
          <a className="contact-card reveal" href="https://github.com/sneezejayhauser" target="_blank" rel="noreferrer">
            <AtSign size={22} />
            <div><h3>GitHub</h3><p>@sneezejayhauser</p></div>
            <ArrowUpRight size={17} />
          </a>
          <a className="contact-card reveal" style={{ '--reveal-delay': '100ms' }} href="https://www.instagram.com/sneezejayhauser" target="_blank" rel="noreferrer">
            <Camera size={22} />
            <div><h3>Instagram</h3><p>@sneezejayhauser</p></div>
            <ArrowUpRight size={17} />
          </a>
          <div className="contact-card contact-note reveal" style={{ '--reveal-delay': '200ms' }}>
            <Mail size={22} />
            <div><h3>Everything else</h3><p>Find CJ on the court, in the pool, or mid gacha pull.</p></div>
            <Dumbbell size={17} />
          </div>
        </div>
      </section>

      <footer>
        <span>CJ · anime games enthusiast</span>
        <span>Built with Codex · <Heart size={11} /> and zero regrets about the fun fact</span>
      </footer>
    </main>
  </>;
}

function SplashScreen({ onFinish }) {
  const [closing, setClosing] = useState(false);
  useEffect(() => {
    const closeTimer = window.setTimeout(() => setClosing(true), 10500);
    const finishTimer = window.setTimeout(onFinish, 12500);
    return () => { window.clearTimeout(closeTimer); window.clearTimeout(finishTimer); };
  }, []);
  return (
    <div className={`splash-screen ${closing ? 'splash-closing' : ''}`} role="dialog" aria-label="Welcome">
      <div className="splash-content">
        <p className="splash-line splash-brand"><SplashText text="CJ" /></p>
        <p className="splash-line splash-meta"><SplashText text="A PERSON WHO PLAYS ANIME GAMES TOO MUCH" /></p>
        <p className="splash-line splash-credit"><SplashText text="Presented to you by Sneeze Hauser" /></p>
      </div>
    </div>
  );
}

function SplashText({ text }) {
  return [...text].map((character, index) => (
    <span className="splash-letter" style={{ '--letter-index': index }} key={`${character}-${index}`}>
      {character === ' ' ? ' ' : character}
    </span>
  ));
}

createRoot(document.getElementById('root')).render(<App />);
